### ISSUE TITLE
Reply from headers buf with open xwidgets view uses headers buf, not view buf

### ISSUE THREAD

**Issue by ellingtonjp** [lordpretzel/mu4e-views#11]
### Desired behavior

With both header & view buffer open using xwidgets, `mu4e-compose-reply` from headers buffer uses the **view** buffer, not the **header** buffer.

### Actual behavior

`mu4e-compose-reply` uses the headers buffer:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/15021649/104823518-884da900-57ff-11eb-9555-5e9e5c5b7930.png">

### Steps to reproduce

1. `mu4e-views-select-view-msg-method` html
2. open headers buffer
3. `mu4e-headers-view-message` on any message
4. switch to headers buffer if not already there
5. `mu4e-compose-reply`

### Bug present In
Current master (1/16/20) `55e5467`

### Cause

* `mu4e-compose-reply` uses `mu4e-compose`
* `mu4e-compose` uses the view's **buffer name** to decide whether to use it for replies
* normally, the view buffer name is `*mu4e-view*`, but when using xwidgets it is `*xwidget webkit:  *`

### Hack workaround

in the `mu4e` package, change `mu4e/mu4e-compose.el:776` (in the `mu4e-compose`function) change:
```
(let ((viewwin (get-buffer-window (mu4e-get-view-buffer))))
```
to 
```
(let ((viewwin (get-buffer-window "*xwidget webkit:  *")))
```

### Notes

Not really sure what the best way to fix this is. I tried renaming the xwidget buffer to `*mu4e-view*` name in various places, but nothing seemed to work.

**Comment by ellingtonjp** [comment]
A better workaround is to place this in your config:

```
(defun mu4e-xwidgets-compose-hack-advice (orig-fn &rest args)
  (cl-letf (((symbol-function #'mu4e-get-view-buffer)
             (lambda () "*xwidget webkit:  *")))
    (apply orig-fn args)))

(advice-add #'mu4e-compose :around #'mu4e-xwidgets-compose-hack-advice)
```

I guess it will cause problems if you use xwidget for anything else

**Comment by lordpretzel** [comment]
Hi,

In branch `dispatcher-view-method` each view method in mu4e-views has to define a predicate that takes a window as input and returns t if that window is the view window for this method. This is used by mu4e-views internally. In this branch I am advising `mu4e-get-view-buffer` to use the view specific predicate. So this hack should soon no longer be necessary. You can try this branch or wait for me to merge into master after some more testing.

**Comment by ellingtonjp** [comment]
Nice, I'll check out the branch when I get a chance! Thanks

**Comment by lordpretzel** [comment]
This should now be fixed, in case you are you using master, if you can confirm that this now works as advertised, then I'll close the issue.
