### ISSUE TITLE
wrong debug log version 

### ISSUE THREAD

**Issue by fuyu0425** [lordpretzel/mu4e-views#20]
https://github.com/lordpretzel/mu4e-views/blob/c7f2398612218407e72b174f02b26cf2916eba22/mu4e-views.el#L538-L552

Hi, Looks like the order of the two `mu4e-views-debug-log` is wrong.

Thanks for this great package.

**Comment by lordpretzel** [comment]
thanks :-)

I'll have a look

**Comment by lordpretzel** [comment]
fixed in the latest commits
