### ISSUE TITLE
"html-nonblock" still filters messages when used in the dispatcher predicate view map

### ISSUE THREAD

**Issue by pkazmier** [lordpretzel/mu4e-views#23]
Messages are still filtered when the view method is set to `"html-nonblock"` in the predicate view map.

To reproduce, set the default predicate view map to **not** filter messages, and open a message that would normally be filtered. Upon opening, the message is still filtered even though `"html-nonblock"` was specified.

```
  (setq mu4e-views-dispatcher-predicate-view-map
        `((,(lambda (msg) (mu4e-message-field msg :body-html)) . "html-nonblock")
          (,(lambda (msg) (ignore msg) t) . "text")))
```

I have confirmed that I am able to view the same messages without filtering using the interactive `mu4e-views-mu4e-view-as-nonblocked-html`. This rules out any issues with specific email content. Further, I have confirmed that if you change `"html-nonblock"` above to `"text"`, the predicate map works as expected showing the plain text alternative.

Finally, I discovered this issue while building my own predicate to prevent filtering of email from senders in a list of case-insensitive domains. At first, I thought this was due to my predicate function until I tested it using the `"text"` view method and realized the predicate was working as expected.

```
  (setq mu4e-views-dispatcher-predicate-view-map
        `((,(lambda (msg)
              (let ((allow-list '("somedomain.com" "anotherdomain.com"))
                    (from-addr (cdar (mu4e-message-field msg :from)))
                    (-compare-fn (-flip (-rpartial #'string-suffix-p t))))
                (-contains-p allow-list from-addr))) . "html-nonblock")  ; If I set to "text", it works as expected
          (,(lambda (msg) (mu4e-message-field msg :body-html)) . "html")
          (,(lambda (msg) (ignore msg) t) . "text")))
```

**Comment by lordpretzel** [comment]
Hi,

thanks for the detailed description. I'll check this. My guess is that I am applying filtering for the dispatcher view like for other views which is confusing. If that is the case then I'll change behavior to avoid filtering in the dispatcher already.
