### ISSUE TITLE
In text mode, it shows ^M

### ISSUE THREAD

**Issue by breadncup** [lordpretzel/mu4e-views#25]
Hi,

When I switch the view mode from "html" to "text", in Text view, it shows "^M" at the end of each line.

I don't see the ^M in without mu4e-views package.

Could you check this out, please?

**Comment by breadncup** [comment]
I realized that gnu mode is working good since the mu4e uses gnu article by default and this makes right.

However, I see there is still an update in mu4e-views for gnu view:

```
--- original-mu4e-views.el	2021-12-08 14:51:57.000000000 -0800
+++ mu4e-views.el	2021-12-08 14:52:17.000000000 -0800
@@ -666,7 +666,8 @@
        (mu4e-message-field msg :path) nil nil nil t)))
   (select-window win)
   (switch-to-buffer gnus-article-buffer t t)
-  (mu4e~view-render-buffer msg))
+  (mu4e~view-render-buffer msg)
+  (mu4e-view-mode))

 (defun mu4e-views-gnus-view-message-before-1.5 (msg win)
   "View message MSG on window WIN using Gnus article mode for mu4e versions before 1.5.x."
```

So that, the article can use the mu4e-view-mode properly. Otherwise, all keyboard shortcuts would be lost when it is focused.

**Comment by breadncup** [comment]
Also, can you use gnus by default instead of text when the dispatcher is selected, please?

**Comment by lordpretzel** [comment]
Hi,

can you let me know what mu4e version and OS you are using? mu4e is only using gnus as the default view in newer versions. I can change the default dispatcher to gnus for newer mu4e versions.

**Comment by breadncup** [comment]
Hi, sorry for the delayed answer. The end of the year makes me really busy.

Here is the information:

```
mu4e-mu-version is a variable defined in ‘mu4e-meta.el’.
Its value is "1.6.8"
```
```
$ sw_vers
ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52
```

Hope this would be helpful.

**Comment by lordpretzel** [comment]
Hi,

no problem. I believe that was a mu4e bug that got resolved in newer versions. If possible can you update to the latest 1.6.x version which I believe is 1.6.10? Let me know whether this does not resolve the issue.
