### ISSUE TITLE
No such file or directory, mu4e-view-old

### ISSUE THREAD

**Issue by joukeHijlkema** [lordpretzel/mu4e-views#29]
Hi,
I wanted to try your package so I used the straight method:

`(use-package mu4e-views
  :straight (mu4e-views :type git :host github :repo "lordpretzel/mu4e-views"))`

However, if I try to use mu4e-views-mu4e-select-view-msg-method emacs complains with:

`No such file or directory, mu4e-view-old`

Any ideas why ?

I'm using:

`This is GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version
 3.24.30, cairo version 1.16.0) of 2022-03-24`

and
`* mu4e - mu for emacs version 1.7.7`

Thanks,

Jouke

**Comment by lordpretzel** [comment]
Hi,

the master branch does not yet have support mu 1.7.x yet. I have support for mu4e 1.7 in the branch `mu-1.7-support`. You can try that branch (I am using it as my daily driver, but want to test a bit more before merging into master.

**Comment by joukeHijlkema** [comment]
That works perfectly. Thank you for all this !

**Comment by rwilson-lib** [comment]
Can you just add support for version 1.8.3

**Comment by lordpretzel** [comment]
yes, I will first continue to develop this in the 1.7.x branch. I haven't adapted it for 1.8.x yet (a lot of functions renamed and so on). furthermore, I haven't fully figured out how gnus attachment system works. It seems that some inlinable attachments are treated differently than ones that are not. I probably won't get to it in the next two weeks, but 1.8.x will be supported in main eventually

**Comment by lordpretzel** [comment]
see #26 where we stand

**Comment by lordpretzel** [comment]
Hi,

I have moved to 1.8.x myself and have created a working version in the `mu-1.8-support` branch. However, there are still some bugs (see #26).
