### ISSUE TITLE
Doesn't interact well with `mu4e-view-use-gnus`

### ISSUE THREAD

**Issue by pymander** [lordpretzel/mu4e-views#3]
I like to use `mu4e-view-use-gnus` for email unless I really want to view HTML. That doesn't seem to interact well with this. Is there a way to get it to work?

**Comment by lordpretzel** [comment]
Do you mean just to provide `mu4e-view-use-gnus` as another view method options? Or do have some other way of interaction in mind?

**Comment by pymander** [comment]
Good question. I really like the way `mu4e-view-use-gnus` handles the headers, and I'd like to keep that. I don't know if that's a possibility though.

**Comment by lordpretzel** [comment]
a ok, let me see whether I understand correctly. So you mean the way gnus show you the headers of the email in the view window like in the screenshot below. If that is what you are looking for, you can achieve that (almost) by customizing the CSS that determines how `mu4e-views` shows the headers (`mu4e-views-mu4e-html-email-header-style`). Currently, there is no way for selecting which headers are shown though (will add this in a future version). 

![headers](https://user-images.githubusercontent.com/2989731/92042776-80093b80-ed40-11ea-8798-bf4cdc2e1700.png)
![mu4eviews](https://user-images.githubusercontent.com/2989731/92043278-674d5580-ed41-11ea-9c30-4204b89e9d41.png)

**Comment by lordpretzel** [comment]
ok, just realize that the view methods does not work if `mu4e-view-use-gnus` is `t`. I'll have to check, but making it respect the existance for mu4e-views should probably not be too hard. In the meanwhile it is probably better to set `mu4e-views-use-gnus` to false until this is fixed.

**Comment by pkazmier** [comment]
I got stumped by this one too. Glad I found this issue because mu4e-views is awesome!!!
