### ISSUE TITLE
mu4e-view-headers-previous does not exists

### ISSUE THREAD

**Issue by fuyu0425** [lordpretzel/mu4e-views#31]
Hi, for the following two advices

https://github.com/lordpretzel/mu4e-views/blob/b02e360d36c54cd9a5f59cdf266be88214a966d2/mu4e-views.el#L2698

https://github.com/lordpretzel/mu4e-views/blob/b02e360d36c54cd9a5f59cdf266be88214a966d2/mu4e-views.el#L2729

I want to point out that the correct mu4e function is `mu4e-view-headers-prev`.

**Comment by lordpretzel** [comment]
Hi, sorry for the slow response. I'm pushing a fix soon.
