### ISSUE TITLE
Wrong number of arguments for mu4e~proc-view

### ISSUE THREAD

**Issue by podiki** [lordpretzel/mu4e-views#5]
This looks like a great package for dealing with all those pesky html emails that don't look right in mu4e. However, when trying it I get the following error `mu4e-views-mu4e-headers-view-message: Wrong number of arguments: #<subr mu4e~proc-view>, 4`. Note that this is on a `native-comp` version of git emacs, so maybe there is something with that or v28 of emacs? This worked on another computer without native compilation. However, when looking at the source, I do see an extra argument of `verify` passed to `mu4e~proc-view` when it only takes at most 3. Removing this fixes the issue for me. Not sure why it worked on another computer though...

**Comment by lordpretzel** [comment]
It is probably not due to emacs 28 or native-comp since I am using also v28 and native-comp. It is probably a mu4e API change. What mu4e version are you using? Then I can lookup the API of this version and add a check (assuming this is the cause of the bug)

**Comment by podiki** [comment]
Oh wow, I last built `mu-git` (on Arch) way back in February (so something like v1.3.6.114.g0dced59c), somehow was missed by my package helper (yay). Probably my other computer was more up to date, or on latest stable mu (v1.4.13). In fact, I think the commits that changed this in mu4e happened like a week later. So probably v1.4.x is the cutoff.

**Comment by lordpretzel** [comment]
ok, that should be easy to fix, I'll have to go through the mu4e commits to find the cutoff when to pass the verify options.

**Comment by podiki** [comment]
Oh, I could have included that for you, here it is (good ol git blame): https://github.com/djcb/mu/commit/36a5d291d999fe6036eb101525546148d281464a

**Comment by lordpretzel** [comment]
thanks!

**Comment by lordpretzel** [comment]
Ok, took me quite a while of finding the time to fix it, but it is finally done. Will push a fix later tonight after testing a bit. I should really setup some testing environment to test with different mu versions.
