### ISSUE TITLE
Different behavior for navigating headers mode than upstream mu4e

### ISSUE THREAD

**Issue by seanfarley** [lordpretzel/mu4e-views#7]
Hi, thanks again for such a cool package :-)

This is a minor nit but when I use `n` and `p` to scroll in the headers mode (no view window), `mu4e-views` seems to open a view window without hitting enter. This is jarring, to me at least, because it's different than upstream's behavior. Oh, and my method for email is `'html`.

It's easy to reproduce on my machine: just press `q` to close the view window and scroll in the headers windows with `n` or `p`. This behavior is different if I set the method to `'text` (which seems to behave as upstream).

**Comment by lordpretzel** [comment]
yes, I guess I could make this configurable through a customization open.

**Comment by seanfarley** [comment]
That'd be much appreciated!

**Comment by seanfarley** [comment]
I'm not sure this should be in the same bug report or not (I feel I've been posting too many already 😰) but marking messages in the view window is also lost in the `'html` mode (but works in `'text`).

**Comment by lordpretzel** [comment]
I think this is just a missing key binding, the minor mode that I defined to add keybindings to the xwidgets view does not copy everything from mu4e. That should be an easy fix.

**Comment by titaniumbones** [comment]
I'd love to see this feature too. I get a lot of useless mail that I would rather delete than look at, and that flow is slowed down by the auto-open.  

Can't believe I finally get to see html mails in mu4e though! This is great.

**Comment by seanfarley** [comment]
Woo, thanks for fixing this!
