### ISSUE TITLE
mu4e-select-other-view is broken

### ISSUE THREAD

**Issue by titaniumbones** [lordpretzel/mu4e-views#9]
mu4e-views breaks `mu4e-select-other-view`, bound by default to `y` in header and view mode.  That function calls `mu4e-get-view-buffer` which is just:

```elisp
(defun mu4e-get-view-buffer ()
  (get-buffer mu4e~view-buffer-name))
```

which returns `nil` when mu4e-views html mode is active. 

It would be nice to have a drop-in replacement that searched first for the xwidget buffer and only afterwards for the default view buffer.  Looking very, very quickly at our code I don't immediately see a way to do this but I hope it's possible!

**Comment by lordpretzel** [comment]
That should be not too hard to fix I think

**Comment by lordpretzel** [comment]
Turns out that I had to advice `mu4e-select-other-view` directly because it checks whether for `'mu4e-view-mode`, but the html view window is in `xwidgets` mode. I have a commit that fixes it. I'll push it to master later tonight after testing a bit more.
